# ======================================================================
# Required software packages
# ======================================================================
- name: enable epel repository
  yum:
    name: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
    state: present

- name: install required packages
  yum:
    name: "{{ item }}"
  with_items:
  - python-devel
  - python-pip
  - gcc

- name: install pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
  - ecdsa
  - markupsafe
  - ansible

# ======================================================================
# Copy ansible configuration file
# ======================================================================
- name: ensure ansible configuration directory
  file:
    path: /etc/ansible
    state: directory

- name: copy ansible configuration
  copy:
    src: ansible.cfg
    dest: /etc/ansible/ansible.cfg

# ======================================================================
# Install keychain for proper ssh agents
# ======================================================================
- name: register rpmforge key
  rpm_key:
    key: http://dag.wieers.com/rpm/packages/RPM-GPG-KEY.dag.txt

- name: install the repo file
  copy:
    src: "{{ item }}.repo"
    dest: /etc/yum.repos.d/{{ item }}.repo
  with_items:
  - rpmforge

- name: install keychain
  yum:
    name: keychain
    enablerepo: rpmforge

- name: place keychain.sh in /etc/profile.d
  copy:
    src: keychain.sh
    dest: /etc/profile.d/keychain.sh

# ======================================================================
# Prepare hostfiles directory
# ======================================================================
- name: create ansible hosts directory
  file:
    path: /etc/ansible/hosts.d
    state: directory
